config:
  target: 'http://localhost:5001'
  phases:
    - duration: 60
      arrivalRate: 10
      name: "Warm up phase"
    - duration: 120
      arrivalRate: 50
      name: "Sustained load phase"
    - duration: 60
      arrivalRate: 100
      name: "Peak load phase"
    - duration: 30
      arrivalRate: 10
      name: "Cool down phase"
  defaults:
    headers:
      Content-Type: 'application/json'
  processor: './load-test-processor.js'

scenarios:
  - name: "Example API Load Test"
    weight: 100
    flow:
      - get:
          url: "/api/v1/example"
          qs:
            page: 1
            limit: 10
          expect:
            - statusCode: 200
            - contentType: json
            - hasProperty: items
            - hasProperty: total
      
      - post:
          url: "/api/v1/example"
          json:
            name: "Load Test Example {{ $randomString() }}"
            type: "LoadTest"
          expect:
            - statusCode: 201
            - contentType: json
            - hasProperty: _id
            - hasProperty: name
            - hasProperty: type
      
      - get:
          url: "/api/v1/example"
          qs:
            page: 1
            limit: 5
            search: "LoadTest"
          expect:
            - statusCode: 200
            - contentType: json
      
      - think: 1
      
      - get:
          url: "/api/v1/example"
          qs:
            page: 2
            limit: 5
          expect:
            - statusCode: 200
            - contentType: json

  - name: "Health Check Load Test"
    weight: 20
    flow:
      - get:
          url: "/api/v1/health"
          expect:
            - statusCode: 200
            - contentType: json
            - hasProperty: status
      
      - think: 2

  - name: "Error Handling Load Test"
    weight: 10
    flow:
      - get:
          url: "/api/v1/tab"
          qs:
            page: "invalid"
            limit: "invalid"
          expect:
            - statusCode: 400
      
      - post:
          url: "/api/v1/example"
          json:
            name: ""
            type: ""
          expect:
            - statusCode: 400
      
      - get:
          url: "/api/v1/nonexistent"
          expect:
            - statusCode: 404
      
      - think: 1 